services:
  reth-node:
    # use build . if you want to use hot-reload from changes made to the source code.
    #build: .
    image: ghcr.io/evstack/ev-reth:latest
    container_name: reth-dev
    entrypoint: [ "sh", "-c", "if [ ! -f /data/jwt.hex ] || [ ! -s /data/jwt.hex ]; then cp /shared/reth-jwt-secret.txt /data/jwt.hex; fi && ev-reth node --engine.persistence-threshold 0 --engine.memory-block-buffer-target 0 --engine.always-process-payload-attributes-on-canonical-head --chain /chain/genesis.json --metrics 0.0.0.0:9001 --log.file.directory /data/logs --authrpc.addr 0.0.0.0 --authrpc.port 8551 --authrpc.jwtsecret /data/jwt.hex --http --http.addr 0.0.0.0 --http.port 8545 --http.api eth,net,web3,txpool --ws --ws.addr 0.0.0.0 --ws.port 8546 --ws.api eth,net,web3 --disable-discovery --txpool.pending-max-count 200000 --txpool.pending-max-size 200 --txpool.queued-max-count 200000 --txpool.queued-max-size 200 --txpool.max-account-slots 2048 --txpool.max-new-txns 2048 --txpool.additional-validation-tasks 16 --ev-reth.enable --datadir /data" ]
    ports:
      - "8545:8545"
      - "8546:8546"
      - "8551:8551"
      - "9001:9001"
    volumes:
      - reth-data:/data
      - jwt-tokens:/shared
      - ./chain:/chain:ro
    environment:
      - RUST_LOG=info,reth=info
    networks:
      - rollup-network
    restart: unless-stopped

volumes:
  reth-data:
  jwt-tokens:
    external: true

networks:
  rollup-network:
    external: true
